//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace rr2.Web.newsInfo {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblnewsId;
	protected global::System.Web.UI.WebControls.Label lbluserId;
	protected global::System.Web.UI.WebControls.Label lblTypeId;
	protected global::System.Web.UI.WebControls.Label lblnewsTitle;
	protected global::System.Web.UI.WebControls.Label lblnewsContent;
	protected global::System.Web.UI.WebControls.Label lblnewsCount;
	protected global::System.Web.UI.WebControls.Label lblnewsReleaseTime;
	protected global::System.Web.UI.WebControls.Label lblext1;
	protected global::System.Web.UI.WebControls.Label lblext2;
	protected global::System.Web.UI.WebControls.Label lblext3;


       
    }
}
