//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace rr2.Web.NewInfo {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblnewId;
	protected global::System.Web.UI.WebControls.Label lblnewTitle;
	protected global::System.Web.UI.WebControls.Label lblnewCoutent;
	protected global::System.Web.UI.WebControls.Label lbltypeId;
	protected global::System.Web.UI.WebControls.Label lbluserId;
	protected global::System.Web.UI.WebControls.Label lblnewTime;
	protected global::System.Web.UI.WebControls.Label lblnewNR;


       
    }
}
