//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace rr2.Web.userInfo {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtuserLoginName;
		protected global::System.Web.UI.WebControls.TextBox txtuserTrueName;
		protected global::System.Web.UI.WebControls.TextBox txtuserPass;
		protected global::System.Web.UI.WebControls.TextBox txtuserEmail;
		protected global::System.Web.UI.WebControls.TextBox txtuserTel;
		protected global::System.Web.UI.WebControls.TextBox txtflag;
		protected global::System.Web.UI.WebControls.TextBox txtext1;
		protected global::System.Web.UI.WebControls.TextBox txtext2;
		protected global::System.Web.UI.WebControls.TextBox txtext3;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
