//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace rr2.Web.userInfo {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lbluserId;
	protected global::System.Web.UI.WebControls.Label lbluserLoginName;
	protected global::System.Web.UI.WebControls.Label lbluserTrueName;
	protected global::System.Web.UI.WebControls.Label lbluserPass;
	protected global::System.Web.UI.WebControls.Label lbluserEmail;
	protected global::System.Web.UI.WebControls.Label lbluserTel;
	protected global::System.Web.UI.WebControls.Label lblflag;
	protected global::System.Web.UI.WebControls.Label lblext1;
	protected global::System.Web.UI.WebControls.Label lblext2;
	protected global::System.Web.UI.WebControls.Label lblext3;


       
    }
}
